In [82]:
import torch
print(torch.__version__)

2.5.1+cu121


In [83]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


In [84]:
## Using Empty

A=torch.empty(2,3)

In [85]:
## check type

type(A)

torch.Tensor

In [86]:
## Using Zeros

print(torch.zeros(3,3))

## Using Ones

print(torch.zeros(3,3))

## Using Random

print(torch.rand(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9507, 0.8572, 0.8194],
        [0.4068, 0.9327, 0.0709],
        [0.6742, 0.7810, 0.8943]])


In [87]:
## Using Random and Seed

torch.manual_seed(120)

print(torch.rand(3,3))

tensor([[0.5566, 0.5807, 0.3175],
        [0.2012, 0.6687, 0.7744],
        [0.1485, 0.1320, 0.8265]])


In [88]:
## Using Tensor

print(torch.tensor([[1,2,3],[2,3,5]]))

## arrange

print(torch.arange(0,10,2))

## linspace

print(torch.linspace(0,10,10))

## full 

print(torch.full((3,3),5))


## eye for creating identity matrix

print(torch.eye(5))

tensor([[1, 2, 3],
        [2, 3, 5]])
tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Tensor Shapes

In [89]:
Y=torch.empty(3,3)

Y.shape

torch.Size([3, 3])

### `If you want create tensor of same shape and size you can use it`

In [90]:
print(torch.rand_like(Y))

print(torch.empty_like(Y))

print(torch.zeros_like(Y))

tensor([[0.6202, 0.4214, 0.5804],
        [0.0514, 0.8384, 0.7322],
        [0.5923, 0.3191, 0.7236]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## `Find Data Types of Tensor`

In [91]:
Y.dtype

torch.float32

### `Assign Data Type`

In [92]:
X=torch.arange(0,10,1,dtype=torch.int8)

In [93]:
X.to(torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [94]:
X=torch.rand(6,6)
Y=torch.rand(6,6)

In [95]:
Addition_XY=X+2*Y
print("Addition:",Addition_XY)

Subtraction_XY=5*X-Y
print("\n \n Subtraction:",Subtraction_XY)

Addition: tensor([[1.8985, 1.8208, 0.2787, 1.4055, 1.1808, 2.2056],
        [2.0015, 1.5762, 1.3265, 1.6434, 2.5184, 1.7183],
        [1.2730, 2.9731, 1.2076, 1.6042, 1.5271, 1.4867],
        [1.0733, 0.6261, 0.5587, 1.6329, 0.8946, 0.6663],
        [1.5811, 1.3178, 0.7979, 1.6741, 1.8344, 1.5221],
        [0.3625, 0.8495, 2.1186, 1.4896, 0.4103, 0.8246]])

 
 Subtraction: tensor([[-0.8488,  3.9915,  0.7637,  0.4512, -0.5777,  2.2350],
        [ 2.3837,  1.4394,  4.8128, -0.0383,  3.5182,  1.5945],
        [ 4.0447,  3.8735,  1.8284,  3.8840,  2.5012,  1.3241],
        [ 0.4557,  0.4326,  1.6920, -0.0201, -0.3605,  2.3707],
        [-0.4427,  2.0408,  1.8837, -0.6733, -0.5839,  4.1737],
        [ 0.1075,  2.5587,  2.3796,  1.0459, -0.1592, -0.2416]])


In [96]:
print(torch.round(X))
print(torch.floor(X))
print(torch.ceil(X))

tensor([[0., 1., 0., 0., 0., 1.],
        [1., 0., 1., 0., 1., 0.],
        [1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 1., 1., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
