In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 3050 Laptop GPU


In [4]:
## Using Empty

A=torch.empty(2,3)

In [5]:
## check type

type(A)

torch.Tensor

In [6]:
## Using Zeros

print(torch.zeros(3,3))

## Using Ones

print(torch.zeros(3,3))

## Using Random

print(torch.rand(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9672, 0.2102, 0.7755],
        [0.7620, 0.0417, 0.2405],
        [0.7945, 0.6527, 0.7426]])


In [7]:
## Using Random and Seed

torch.manual_seed(120)

print(torch.rand(3,3))

tensor([[0.5566, 0.5807, 0.3175],
        [0.2012, 0.6687, 0.7744],
        [0.1485, 0.1320, 0.8265]])


In [8]:
## Using Tensor

print(torch.tensor([[1,2,3],[2,3,5]]))

## arrange

print(torch.arange(0,10,2))

## linspace

print(torch.linspace(0,10,10))

## full 

print(torch.full((3,3),5))


## eye for creating identity matrix

print(torch.eye(5))

tensor([[1, 2, 3],
        [2, 3, 5]])
tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Tensor Shapes

In [9]:
Y=torch.empty(3,3)

Y.shape

torch.Size([3, 3])

### `If you want create tensor of same shape and size you can use it`

In [10]:
print(torch.rand_like(Y))

print(torch.empty_like(Y))

print(torch.zeros_like(Y))

tensor([[0.6202, 0.4214, 0.5804],
        [0.0514, 0.8384, 0.7322],
        [0.5923, 0.3191, 0.7236]])
tensor([[2.4365e-27, 8.1275e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## `Find Data Types of Tensor`

In [11]:
Y.dtype

torch.float32

### `Assign Data Type`

In [12]:
X=torch.arange(0,10,1,dtype=torch.int8)

In [13]:
X.to(torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [14]:
X=torch.rand(6,6)
Y=torch.rand(6,6)

In [15]:
Addition_XY=X+2*Y
print("Addition:",Addition_XY)

Subtraction_XY=5*X-Y
print("\n \n Subtraction:",Subtraction_XY)

Addition: tensor([[1.8985, 1.8208, 0.2787, 1.4055, 1.1808, 2.2056],
        [2.0015, 1.5762, 1.3265, 1.6434, 2.5184, 1.7183],
        [1.2730, 2.9731, 1.2076, 1.6042, 1.5271, 1.4867],
        [1.0733, 0.6261, 0.5587, 1.6329, 0.8946, 0.6663],
        [1.5811, 1.3178, 0.7979, 1.6741, 1.8344, 1.5221],
        [0.3625, 0.8495, 2.1186, 1.4896, 0.4103, 0.8246]])

 
 Subtraction: tensor([[-0.8488,  3.9915,  0.7637,  0.4512, -0.5777,  2.2350],
        [ 2.3837,  1.4394,  4.8128, -0.0383,  3.5182,  1.5945],
        [ 4.0447,  3.8735,  1.8284,  3.8840,  2.5012,  1.3241],
        [ 0.4557,  0.4326,  1.6920, -0.0201, -0.3605,  2.3707],
        [-0.4427,  2.0408,  1.8837, -0.6733, -0.5839,  4.1737],
        [ 0.1075,  2.5587,  2.3796,  1.0459, -0.1592, -0.2416]])


In [16]:
print(torch.round(X))
print(torch.floor(X))
print(torch.ceil(X))

tensor([[0., 1., 0., 0., 0., 1.],
        [1., 0., 1., 0., 1., 0.],
        [1., 1., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 1., 1., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


#### To Fix a Matrix between some values we use `clamp`

In [18]:
torch.clamp(Addition_XY*1.5,min=2,max=3)

tensor([[2.8477, 2.7312, 2.0000, 2.1082, 2.0000, 3.0000],
        [3.0000, 2.3643, 2.0000, 2.4651, 3.0000, 2.5775],
        [2.0000, 3.0000, 2.0000, 2.4064, 2.2907, 2.2300],
        [2.0000, 2.0000, 2.0000, 2.4493, 2.0000, 2.0000],
        [2.3717, 2.0000, 2.0000, 2.5112, 2.7516, 2.2831],
        [2.0000, 2.0000, 3.0000, 2.2343, 2.0000, 2.0000]])

In [30]:
E=torch.randint(size=(8,5),low=0,high=10,dtype=torch.float64)

E

tensor([[2., 7., 8., 1., 5.],
        [9., 6., 6., 6., 8.],
        [7., 3., 1., 1., 6.],
        [3., 9., 3., 1., 3.],
        [7., 3., 9., 1., 2.],
        [2., 5., 9., 0., 1.],
        [8., 7., 7., 6., 5.],
        [4., 0., 6., 1., 9.]], dtype=torch.float64)

#### Reduction Operation like `sum` , `sum along rows`, `sum along columns`

In [31]:
print("SUM: ", torch.sum(E))

print("SUM along columns: ", torch.sum(E,dim=0))

print("SUM along rows:", torch.sum(E,dim=1))

SUM:  tensor(187., dtype=torch.float64)
SUM along columns:  tensor([42., 40., 49., 17., 39.], dtype=torch.float64)
SUM along rows: tensor([23., 35., 18., 19., 22., 17., 33., 20.], dtype=torch.float64)


#### Reduction Operation like `mean` , `mean along rows`, `mean along columns`

In [36]:
print("Mean: ", torch.mean(E))

print("Mean along columns: ", torch.mean(E,dim=0))

print("Mean along rows:", torch.mean(E,dim=1))

print('\n\n')

print("Median: ", torch.median(E))

print("Median along columns: ", torch.median(E,dim=0))

print("Median along rows:", torch.median(E,dim=1))

Mean:  tensor(4.6750, dtype=torch.float64)
Mean along columns:  tensor([5.2500, 5.0000, 6.1250, 2.1250, 4.8750], dtype=torch.float64)
Mean along rows: tensor([4.6000, 7.0000, 3.6000, 3.8000, 4.4000, 3.4000, 6.6000, 4.0000],
       dtype=torch.float64)



Median:  tensor(5., dtype=torch.float64)
Median along columns:  torch.return_types.median(
values=tensor([4., 5., 6., 1., 5.], dtype=torch.float64),
indices=tensor([7, 5, 7, 3, 0]))
Median along rows: torch.return_types.median(
values=tensor([5., 6., 3., 3., 3., 2., 7., 4.], dtype=torch.float64),
indices=tensor([4, 3, 1, 2, 1, 0, 1, 0]))


In [ ]:
print('Max: ', torch.max(E), 'Min:',torch.min(E))

Max:  tensor(9., dtype=torch.float64) Min: tensor(0., dtype=torch.float64)


In [41]:
torch.max(E,dim=0)

torch.return_types.max(
values=tensor([9., 9., 9., 6., 9.], dtype=torch.float64),
indices=tensor([1, 3, 4, 1, 7]))

In [ ]:
torch.prod(E)

tensor(0)

In [51]:
print("STD: ",torch.std(E))

print("VAR: ",torch.var(E))

STD:  tensor(2.9473, dtype=torch.float64)
VAR:  tensor(8.6865, dtype=torch.float64)


In [53]:
torch.argmax(E)

torch.argmin(E)

tensor(28)

## `Matrix Operation`

In [64]:
A=torch.randint(size=(6,3),low=1,high=22,dtype=torch.float32)
B=torch.randint(size=(3,6),low=12,high=34,dtype=torch.float32)

In [65]:
torch.matmul(A,B)

tensor([[ 605.,  907., 1036.,  919., 1016.,  772.],
        [ 206.,  246.,  208.,  286.,  244.,  240.],
        [ 281.,  324.,  346.,  378.,  328.,  375.],
        [ 977., 1202., 1186., 1362., 1233., 1220.],
        [ 786.,  849.,  858., 1031.,  828., 1041.],
        [ 193.,  265.,  296.,  281.,  288.,  250.]])

In [72]:
torch.transpose(B,0,1)

tensor([[12., 22., 23.],
        [27., 21., 25.],
        [30., 26., 16.],
        [23., 27., 31.],
        [33., 20., 23.],
        [12., 33., 25.]])

#### Calculating $Determinant$

In [78]:
C=torch.randint(size=(6,6),low=1,high=22,dtype=torch.float32)

torch.det(C)

tensor(-7084216.)

In [82]:
torch.inverse(C)

tensor([[-3.3745e-02,  3.2542e-02,  1.3262e-02, -5.5993e-02, -8.9798e-03,
          5.6902e-02],
        [-3.5134e-02,  9.7122e-02, -1.1835e-02, -6.7509e-02, -1.7834e-01,
          1.3579e-01],
        [ 3.4780e-02, -7.1745e-02, -1.0812e-02,  1.5482e-01,  1.7914e-01,
         -1.9214e-01],
        [-4.2325e-03,  4.1094e-02,  4.7510e-02, -6.0701e-02, -7.5820e-02,
          4.8098e-02],
        [-1.1858e-04, -7.3755e-02,  2.8345e-02,  1.7310e-02,  2.8225e-02,
          2.5027e-02],
        [ 7.2264e-02, -3.6868e-02, -4.2899e-02,  3.9986e-02,  8.9749e-02,
         -7.9883e-02]])

### We can calculate `exponent`, `Squareroot`,`Sigmoid`

In [ ]:
printtorch.exp(C)

torch.sigmoid(C)

tensor([[0.9975, 1.0000, 0.9991, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.7311, 1.0000],
        [0.9997, 0.9933, 1.0000, 1.0000, 0.9999, 0.8808],
        [0.9999, 1.0000, 1.0000, 0.9820, 1.0000, 0.9975],
        [1.0000, 0.9975, 0.9997, 0.8808, 0.9975, 0.9999],
        [1.0000, 1.0000, 1.0000, 0.9526, 1.0000, 1.0000]])