In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [4]:
X_train,X_test,y_train,y_test=train_test_split(df.drop('diagnosis',axis=1),df['diagnosis'],test_size=0.2)

In [5]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [6]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

## Numpy to Torch Tensor 

In [7]:
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

In [46]:
learning_rate=0.1
epochs=25

### Using `torch.nn`

In [9]:
import torch.nn as nn

In [16]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        # Convert input to float32 to match weight types
        features = features.float() 
        
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [17]:
X_train.shape

torch.Size([455, 30])

In [18]:
model=Model(X_train.shape[1])

In [19]:
model(X_train)

tensor([[0.5865],
        [0.4753],
        [0.4262],
        [0.6249],
        [0.6051],
        [0.5326],
        [0.6176],
        [0.4350],
        [0.4686],
        [0.3630],
        [0.5393],
        [0.4013],
        [0.5696],
        [0.5648],
        [0.5095],
        [0.4109],
        [0.3651],
        [0.6190],
        [0.3976],
        [0.5412],
        [0.5281],
        [0.5906],
        [0.6262],
        [0.5673],
        [0.3453],
        [0.3282],
        [0.3676],
        [0.7577],
        [0.6714],
        [0.7344],
        [0.5753],
        [0.5991],
        [0.4435],
        [0.4428],
        [0.6392],
        [0.4331],
        [0.5663],
        [0.5482],
        [0.5600],
        [0.6923],
        [0.6163],
        [0.5222],
        [0.5667],
        [0.5347],
        [0.4105],
        [0.2521],
        [0.3538],
        [0.2950],
        [0.3976],
        [0.4589],
        [0.5892],
        [0.4601],
        [0.4318],
        [0.3575],
        [0.7513],
        [0

In [22]:
model.linear.weight

Parameter containing:
tensor([[ 1.1902e-01, -3.7342e-05, -1.5269e-01,  7.4766e-03,  1.4983e-01,
         -1.0595e-01, -1.4289e-02,  5.0171e-02,  1.7530e-01,  1.5977e-01,
          6.0674e-02, -5.9230e-03,  1.1697e-02,  1.7400e-01, -1.1913e-01,
         -2.0301e-02,  3.0888e-02, -1.6609e-01,  1.6682e-01,  1.1478e-02,
         -5.6829e-02,  2.8467e-02, -1.5790e-01, -1.5657e-01,  1.0765e-02,
         -1.0896e-01, -8.5537e-02, -1.2240e-02,  3.0942e-02,  1.9072e-02]],
       requires_grad=True)

In [23]:
model.linear.bias

Parameter containing:
tensor([0.1408], requires_grad=True)

In [26]:
from torchinfo import summary

In [27]:
summary(model,input_size=X_train.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (M): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06

### <br>With Hidden Layer</br>

In [29]:
class Model_2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear_1 = nn.Linear(num_features, 60)
        self.relu=nn.ReLU()
        self.linear_2=nn.Linear(60,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        # Convert input to float32 to match weight types
        features = features.float() 
        
        out = self.linear_1(features)
        out = self.relu(out)
        out = self.linear_2(out)
        out = self.sigmoid(out)
        return out

In [30]:
model=Model_2(X_train.shape[1])

In [31]:
model(X_train)

tensor([[0.4770],
        [0.5078],
        [0.5427],
        [0.3625],
        [0.4847],
        [0.5163],
        [0.3997],
        [0.5009],
        [0.5280],
        [0.5210],
        [0.4688],
        [0.5130],
        [0.4022],
        [0.4936],
        [0.5002],
        [0.5322],
        [0.4474],
        [0.4640],
        [0.5590],
        [0.4730],
        [0.4656],
        [0.4443],
        [0.4883],
        [0.3794],
        [0.4381],
        [0.5001],
        [0.4527],
        [0.4952],
        [0.4700],
        [0.4878],
        [0.5079],
        [0.4652],
        [0.5478],
        [0.4487],
        [0.4526],
        [0.5201],
        [0.5132],
        [0.4690],
        [0.5015],
        [0.3708],
        [0.4272],
        [0.4311],
        [0.5088],
        [0.4775],
        [0.5486],
        [0.4869],
        [0.5661],
        [0.4860],
        [0.5359],
        [0.5588],
        [0.5292],
        [0.4679],
        [0.5306],
        [0.4279],
        [0.4771],
        [0

In [32]:
summary(model=model,input_size=X_train.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model_2                                  [455, 1]                  --
├─Linear: 1-1                            [455, 60]                 1,860
├─ReLU: 1-2                              [455, 60]                 --
├─Linear: 1-3                            [455, 1]                  61
├─Sigmoid: 1-4                           [455, 1]                  --
Total params: 1,921
Trainable params: 1,921
Non-trainable params: 0
Total mult-adds (M): 0.87
Input size (MB): 0.05
Forward/backward pass size (MB): 0.22
Params size (MB): 0.01
Estimated Total Size (MB): 0.28

### Using `Sequential`

In [37]:
class Model_3(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(
        nn.Linear(num_features, 60),
        nn.ReLU(),
        nn.Linear(60,1),
        nn.Sigmoid()
        )
       

    def forward(self, features):
        # Convert input to float32 to match weight types
        features = features.float() 
        out = self.network(features)
        return out

In [38]:
model=Model_3(X_train.shape[1])

In [39]:
model(X_train)

tensor([[0.5221],
        [0.5604],
        [0.4930],
        [0.5748],
        [0.5494],
        [0.5401],
        [0.5686],
        [0.3962],
        [0.4761],
        [0.4933],
        [0.4413],
        [0.5172],
        [0.5342],
        [0.4859],
        [0.4704],
        [0.5247],
        [0.4958],
        [0.5857],
        [0.4737],
        [0.4896],
        [0.5547],
        [0.5497],
        [0.4927],
        [0.4740],
        [0.5309],
        [0.4940],
        [0.4488],
        [0.5358],
        [0.5545],
        [0.5805],
        [0.5311],
        [0.4879],
        [0.4982],
        [0.5814],
        [0.5373],
        [0.5375],
        [0.5548],
        [0.4975],
        [0.5420],
        [0.5163],
        [0.5264],
        [0.5013],
        [0.5482],
        [0.5216],
        [0.4420],
        [0.3948],
        [0.4135],
        [0.4640],
        [0.5273],
        [0.5275],
        [0.5531],
        [0.5104],
        [0.5461],
        [0.5989],
        [0.5569],
        [0

In [41]:
summary(model=model,input_size=X_train.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model_3                                  [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 60]                 1,860
│    └─ReLU: 2-2                         [455, 60]                 --
│    └─Linear: 2-3                       [455, 1]                  61
│    └─Sigmoid: 2-4                      [455, 1]                  --
Total params: 1,921
Trainable params: 1,921
Non-trainable params: 0
Total mult-adds (M): 0.87
Input size (MB): 0.05
Forward/backward pass size (MB): 0.22
Params size (MB): 0.01
Estimated Total Size (MB): 0.28

### Actual Training Scenario 

In [51]:
class Neural_Network(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(
        nn.Linear(num_features, 60),
        nn.ReLU(),
        nn.Linear(60,1),
        nn.Sigmoid()
        )
       

    def forward(self, features):
        # Convert input to float32 to match weight types
        features = features.float() 
        out = self.network(features)
        return out
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
        return loss

In [52]:
training_model= Neural_Network(X_train.shape[1])

In [53]:
for epoch in range(1000):
    # 1. Forward pass (calling the model directly is better than .forward())
    y_pred = training_model(X_train)

    # 2. Calculate loss
    loss = training_model.loss_function(y_pred, y_train)

    # 3. Backward pass (calculates gradients)
    loss.backward()

    # 4. Manual Gradient Descent
    with torch.no_grad():
        for param in training_model.parameters():
            # Update the weights/biases
            param -= learning_rate * param.grad
            
            # IMPORTANT: Manually zero the gradients after the update
            # PyTorch accumulates gradients, so if you don't zero them, 
            # the next epoch's gradients will be added to these ones.
            param.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss {loss.item()}")

Epoch 0: Loss 0.6898123621940613
Epoch 10: Loss 0.6714882254600525
Epoch 20: Loss 0.6695539355278015
Epoch 30: Loss 0.6690465211868286
Epoch 40: Loss 0.6687359809875488
Epoch 50: Loss 0.6684930920600891
Epoch 60: Loss 0.6682928800582886
Epoch 70: Loss 0.6681235432624817
Epoch 80: Loss 0.6679782867431641
Epoch 90: Loss 0.6678519248962402
Epoch 100: Loss 0.6677409410476685
Epoch 110: Loss 0.6676424145698547
Epoch 120: Loss 0.6675544381141663
Epoch 130: Loss 0.667475163936615
Epoch 140: Loss 0.6674034595489502
Epoch 150: Loss 0.6673383116722107
Epoch 160: Loss 0.6672788858413696
Epoch 170: Loss 0.6672245264053345
Epoch 180: Loss 0.6671746373176575
Epoch 190: Loss 0.6671288013458252
Epoch 200: Loss 0.6670865416526794
Epoch 210: Loss 0.6670475602149963
Epoch 220: Loss 0.6670114398002625
Epoch 230: Loss 0.6669780015945435
Epoch 240: Loss 0.6669469475746155
Epoch 250: Loss 0.6669180393218994
Epoch 260: Loss 0.6668911576271057
Epoch 270: Loss 0.6668660044670105
Epoch 280: Loss 0.66684269905090

In [ ]:
training_model

Neural_Network(
  (network): Sequential(
    (0): Linear(in_features=30, out_features=60, bias=True)
    (1): ReLU()
    (2): Linear(in_features=60, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

#### Using `loss function` and `optim function` given by Torch

In [98]:
class Neural_Network_2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 60),
            nn.ReLU(),
            nn.Linear(60, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        # We explicitly cast to .float() here
        # This solves the "Double vs Float" mismatch by ensuring 
        # the input tensor matches the model's internal weights.
        return self.network(features.float())

### Important Parameters

In [99]:
loss_function=nn.BCELoss()

In [100]:
prod_model=Neural_Network_2(X_train.shape[1])

In [101]:
optimizer=torch.optim.SGD(prod_model.parameters(),lr=learning_rate)

In [105]:
for epoch in range(500):

    # Forward Pass
    y_pred=prod_model(X_train)

    # Loss Calculate
    loss=loss_function(y_pred,y_train.view(-1,1).float())

    # Clear Gradients
    optimizer.zero_grad()

    # Loss Calculation
    loss.backward()
    
    # Parameters Update
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss {loss.item()}")

Epoch 0: Loss 0.023803245276212692
Epoch 10: Loss 0.023646414279937744
Epoch 20: Loss 0.023492176085710526
Epoch 30: Loss 0.023337949067354202
Epoch 40: Loss 0.023186221718788147
Epoch 50: Loss 0.023034701123833656
Epoch 60: Loss 0.022884782403707504
Epoch 70: Loss 0.022736111655831337
Epoch 80: Loss 0.022591304033994675
Epoch 90: Loss 0.022446751594543457
Epoch 100: Loss 0.02230534888803959
Epoch 110: Loss 0.022162558510899544
Epoch 120: Loss 0.02202369086444378
Epoch 130: Loss 0.021890126168727875
Epoch 140: Loss 0.021756405010819435
Epoch 150: Loss 0.02162381447851658
Epoch 160: Loss 0.02149147167801857
Epoch 170: Loss 0.021361716091632843
Epoch 180: Loss 0.021233875304460526
Epoch 190: Loss 0.021106602624058723
Epoch 200: Loss 0.020980175584554672
Epoch 210: Loss 0.020854251459240913
Epoch 220: Loss 0.02073090150952339
Epoch 230: Loss 0.02061009593307972
Epoch 240: Loss 0.020485954359173775
Epoch 250: Loss 0.02036723494529724
Epoch 260: Loss 0.020246997475624084
Epoch 270: Loss 0.0

In [111]:
test=training_model(X_test)

In [ ]:
with torch.no_grad(): 
    
    y_pred = prod_model(X_test)
    
    
    y_pred_class = (y_pred > 0.6).float()
    
    
    correct_predictions = (y_pred_class == y_test.view(-1, 1)).sum().item()
    
    
    accuracy = (correct_predictions / y_test.size(0)) * 100

print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 98.25%
