In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X,y=make_classification(
    n_samples=100,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [3]:
X = torch.tensor(X,dtype=torch.float32)
y= torch.tensor(y,dtype=torch.float32)

In [4]:
from torch.utils.data import Dataset,DataLoader

In [5]:
class CustomDataset(Dataset):

    def __init__(self,features,labels):
        super().__init__()

        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]


In [6]:
dataset = CustomDataset(X,y)

In [8]:
len(dataset)

100

In [9]:
dataset[0]

(tensor([0.5594, 2.3887]), tensor(0.))

In [10]:
dataloader=DataLoader(dataset=dataset,batch_size=5,shuffle=True)

In [12]:
for batch_features, batch_labels in dataloader:
    print(batch_features, batch_labels)
    print("\n---------------------------------\n")

tensor([[-0.3490,  1.5601],
        [ 0.2542, -1.7953],
        [-1.5485, -1.4353],
        [ 0.1551,  1.9981],
        [ 1.0989,  1.2529]]) tensor([0., 1., 0., 0., 1.])

---------------------------------

tensor([[-0.3314,  1.5693],
        [ 0.6806,  1.0270],
        [ 1.0866, -1.0054],
        [-2.0035, -2.3995],
        [-2.3280, -0.1759]]) tensor([0., 1., 1., 0., 0.])

---------------------------------

tensor([[-1.4348, -1.4270],
        [-0.5083,  1.4805],
        [ 0.2506,  0.1398],
        [ 1.0226, -1.0832],
        [-2.0092, -2.2418]]) tensor([0., 0., 1., 1., 0.])

---------------------------------

tensor([[ 0.6653,  0.8863],
        [ 0.3273,  0.6245],
        [-0.8080,  1.1966],
        [ 1.2801,  1.2894],
        [ 0.8260, -1.0538]]) tensor([1., 1., 0., 1., 1.])

---------------------------------

tensor([[ 1.5723,  1.4992],
        [ 1.1787,  1.0918],
        [ 0.8524, -1.1466],
        [ 1.8399,  2.3045],
        [ 2.5912,  0.2447]]) tensor([1., 1., 1., 1., 1.])

-----